[project]
name = "neural-demosaic"
version = "0.1.0"
description = "Neural demosaic for x-trans sensor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.6",
    "pillow>=12.2.0",
    "pyopencl>=2026.1.2",
    "rawler-py>=0.1.2",
    "torch>=2.12.0",
    "kornia>=0.8.3",
    "kornia-rs>=0.1.15rc5",
]
